Inject `global.*` values to make them available to release manager
opendevstack/ods-jenkins-shared-library pull request #1074
Opened 2024-02-20 09:37 UTC by serverhorror

fix #1066

2024-02-26 11:06 UTC, metmajer commented
Thanks @serverhorror and @dvvanessastoiber, we appreciate the fix. FYI @jafarre-bi @hrcornejo

2024-02-26 18:28 UTC, dvvanessastoiber commented
> Doesn't seem to work enough, yet 😔
> 
> Release Manager wants the tag names to be present (the ones it creat s)
> 
> Any hints how those could be forwarded or overwritten so that Helm can receive the right values?

@serverhorror From what I saw in my tests, the generated image tag is correctly set and used. The only thing that is not working for me at the moment is the creation of the image tag in the **frontend** image stream in QA (backend is working).

2024-02-26 18:32 UTC, dvvanessastoiber commented
> Let's take a look, in that case it might be the options used to build the image.
```
...
odsComponentStageBuildOpenShiftImage(
    context, [resourceName: "${context.componentId}-backend", imageTag: "v7.1.1", dockerDir: "docker/backend", buildTimeoutMinutes: 10]
  )
odsComponentStageBuildOpenShiftImage(
    context, [resourceName: "${context.componentId}-frontend", imageTag: "v7.1.1", dockerDir: "docker/frontend", buildTimeoutMinutes: 10]
  )
odsComponentStageRolloutOpenShiftDeployment(context, [
    imageTag: "v7.1.1", 
    deployTimeoutMinutes: 10, 
    selector: "app.kubernetes.io/instance=${context.componentId}",
    chartDir: 'chart',
    helmEnvBasedValuesFiles: [
      'values.env.yaml',
      'secrets.env.yaml'
    ],
    helmAdditionalFlags: ['--debug']
  ])
...
```
The options in the Jenkinsfile are basically the same for frontend and backend

2024-03-04 10:56 UTC, dvvanessastoiber commented
@serverhorror I just wanted to confirm explicitly that this PR is fixing the underlying issue for me. Thank you!

2024-03-05 09:44 UTC, jafarre-bi commented
Hello, @serverhorror @dvvanessastoiber thank you very much for the work you have done here. I think we should talk to clarify any open points. Will contact you offline.

2024-04-22 09:01 UTC, hrcornejo commented
As was said in previous conversations here (and in bug #1066 ), the PR is not enough. The Release Manager needs the tags to be created to process images. Some examples:
We have this image created in DEV:
![image](https://github.com/opendevstack/ods-jenkins-shared-library/assets/16071760/2ee204a6-f353-47dd-8268-2aa36808f2c3)
And after a release to QA, this is the image in the test environment:
![image](https://github.com/opendevstack/ods-jenkins-shared-library/assets/16071760/2dc0d048-d0f8-41f0-93d7-f833c261cced)
The same image (SHA), but with a different tag.
In the example, a CM is using the tag created in DEV, not the one created in QA:
![image](https://github.com/opendevstack/ods-jenkins-shared-library/assets/16071760/b178838d-d237-46c5-bcbb-16f49c8cc927)

2024-04-29 08:32 UTC, hrcornejo requested changes

2024-04-29 08:32 UTC, hrcornejo commented on src/org/ods/component/HelmDeploymentStrategy.groovy
> +                // TODO: is this really needed? - we could use *just* the global ones
Remove the TODOs. Thanks

2024-04-30 08:49 UTC, hrcornejo commented on src/org/ods/component/HelmDeploymentStrategy.groovy
> +                // TODO: is this really needed? - we could use *just* the global ones
Done

2024-04-30 08:50 UTC, hrcornejo approved these changes

2024-04-30 08:51 UTC, merged