Pass inherited branches config to Aqua Stage
opendevstack/ods-jenkins-shared-library pull request #1170
Opened 2024-10-24 10:17 UTC by mobilutz

While debugging an issue where the Aqua stage was ALWAYS run even when the build-stage was not, I stumbled over the issues that the inherited branches config is not being passed to the new Aqua stage that is created.

I tested it on a running jenkins setup, and can say that with this change, I see the following log output:
```
Skipping stage 'Aqua Security Scan' for branch 'prettier' as it is not covered by: 'main', 'review'.
```

I know that a test for this case is missing, but I was not able to install JDK 11 locally, and with any newer JDK version I could not get groovy to work.

Any support on the testing front is greatly appreciated.

2024-10-24 22:40 UTC, gerardcl commented
Hi @mobilutz , you could try using [sdkman](https://sdkman.io/) for the local java env management.

2024-10-25 07:48 UTC, tbugfinder commented
Regarding the develpoment setup I have the same challenges. It's tedious to figure out what's expected and needed. An option might to adding devcontainer setup.

Starting point: https://github.com/opendevstack/ods-jenkins-shared-library/pull/1173/files

2024-11-13 14:35 UTC, gerardcl commented
> > Hi @mobilutz , you could try using [sdkman](https://sdkman.io/) for the local java env management.
> 
> I am not using java in any other project, and I currently only use [`mise`](https://mise.jdx.dev/) as my overall version manager.
> 
> When I try to install JDK 11 with mise, I get the following:
> 
> ```shell
> ❯ mise use java@11
> mise ERROR no metadata found for version 11
> mise ERROR Run with --verbose or MISE_VERBOSE=1 for more information
> ```
> 
> It would be good, to have a possibility like devcontainer os something else that does not rely on a JDK install locally.
> 
> @gerardcl I know that everyone is very busy, but would it be possible to have you are someone else support with writing a test setup for this. I tried to copy things from here, but without running it locally I don't think I can finish the test setup.
> 
> https://github.com/opendevstack/ods-jenkins-shared-library/blob/f5f9d14ca9887c721d9afe17c09b7f5c19a5bde8/test/groovy/vars/OdsComponentStageBuildOpenShiftImageSpec.groovy#L218-L251

hi @mobilutz feel free to connect internally, thanks

2024-12-02 16:30 UTC, metmajer commented
@mobilutz I suggest to follow the devcontainer approach which is already used by some other Quickstarters (inf-terraform) and ODS itself. @BraisVQ can you share the example we have been exchanging with a user in the business?

2024-12-06 17:43 UTC, metmajer commented
By the way, this was the approach @BraisVQ and I wanted to test with regards to devcontainer using Jenkins agent images:

```
{
    "image": "default-route-openshift-image-registry.apps.eu-dev.ocp.aws.boehringer.com/ods/jenkins-agent-python:4.x",
    "postStartCommand": "sleep infinity"
}
```
 
To be able to access this image from your local machine, you will need to login to our OpenShift container image registry in EU first:

```
docker login -u openshift -p $(oc whoami -t) default-route-openshift-image-registry.apps.eu-dev.ocp.aws.boehringer.com
```

It would require some testing though.

2024-12-09 15:28 UTC, mobilutz commented
> @mobilutz could you describe again what your problem with Aqua is?

@metmajer The problem I have is, that the Aqua stage is running even when the build stage was skipped. That means that the image that Aqua should scan is not there and of course it is failing.

Regarding `devcontainers`: I will try to use it, the only problem I have is that I do not have access to OpenShift on my local machine as I am an external-employee and do not use Citrix for my Development Environment :|
I will try it out nevertheless.

2024-12-09 17:10 UTC, metmajer commented
@mobilutz not sure I understand the scenario. Instead of building, what do you do instead? Can you elaborate on the concept of "inherited branches"?

2024-12-10 09:29 UTC, mobilutz commented
> @mobilutz not sure I understand the scenario. Instead of building, what do you do instead? Can you elaborate on the concept of "inherited branches"?

@metmajer I think it is easier with sharing our (redacted) Jenkinsfile that help to show the situatuion:
```
...
odsComponentPipeline(
  ...
  branchToEnvironmentMapping: [
    'master': 'review',
  ],
  ...
) { context ->
  ...
  container('node') {
    ...
  }
  ...
  container('node') {
    stage('Quality Check') {
      parallel (
        ...
        "Tests": {
          sh(
            label: 'Test',
            script: 'npm run test',
          )
        },
        ...
        failFast: true
      )
    }
  }
 ...
}
...
```

As you can see, we are only map `master` to an environment `review`. Only the `master` branch is therefore build with the `BuildOpenShiftImageStage`. That Build-Stage only runs on the `master` branch, and on all other branches it skips because it is not needed.
But in that Build-Stage, the Aqua-Stage is started, and that then ALWAYS run, even when it is not needed.

To prevent the Aqua-Stage to run in this situation, it is needed to pass the branches to the `inheritedConfig`.

I hope that brings more light in the situation that I guess more than we have.

2025-01-21 15:58 UTC, mobilutz commented
This change is still missing specs, I do not see myself writing specs in the near future ☹️ 

But I can say that we are running this change with the help of custom forked-repositories of the `ods-jenkins-shared-library` for a couple of weeks now without any issues.

Maybe someone can support here with writing specs, this change will help developers a lot as the CI pipeline run can be shortened by quite a bit depending on the setup the repository has.

2025-11-06 16:19 UTC, mobilutz commented
@metmajer I added a test with the best of my knowledge.

Could you please look at it, thanks

2025-12-19 10:02 UTC, hrcornejo commented
@metmajer tested succesfully with:
- Component pipeline
- Release Manager Pipeline (Deploy/Re-Deploy).
Please @mobilutz fix the conflict with the CHANGELOG.md file and we'll integrate your changes in  master branch. Thanks!!

2026-04-09 12:42 UTC, mobilutz commented
Thanks @hrcornejo, I almost forgot about this change.

I rebased the changes. You can take a look at it again.

2026-04-09 12:45 UTC, hrcornejo approved these changes

2026-04-09 12:49 UTC, hrcornejo requested changes
Please @mobilutz fix the failing test:
<img width="2475" height="778" alt="image" src="https://github.com/user-attachments/assets/f3a301db-28ba-4f88-8345-948389f3afad" />

2026-04-13 05:55 UTC, hrcornejo approved these changes

2026-04-13 05:55 UTC, merged