Bugfix EDPC-306: Fix NotSerializableException while creating TCP document
opendevstack/ods-jenkins-shared-library pull request #538
Opened 2020-12-10 14:47 UTC by jafarre-viewnext

2020-12-11 08:09 UTC, stitakis approved these changes

2020-12-11 11:19 UTC, metmajer requested changes
@jafarre-viewnext can you please make the method private and use a return statement?

2020-12-15 02:04 UTC, jafarre-viewnext commented
> @jafarre-viewnext can you please make the method private and use a return statement?

Done

2020-12-16 09:07 UTC, metmajer approved these changes
@jafarre-viewnext thanks for the fix. Those issues will keep arising depending on the dynamics of your system. Over time, we will have to make iterator-heavy code like this @NonCPS'ed to be safe, since those are not serializable.

2020-12-16 09:11 UTC, merged