non serializable exeption
opendevstack/ods-jenkins-shared-library pull request #653
Opened 2021-05-18 21:06 UTC by s2oBCN

Add NonCPS to solve serializable exception

2021-05-18 21:16 UTC, clemensutschig commented
@s2oBCN Cool.. does that do  now?

2021-05-19 06:05 UTC, s2oBCN commented
> @s2oBCN Cool.. does that do now?

Now it's working fine

2021-05-19 07:00 UTC, metmajer requested changes

2021-05-19 07:00 UTC, metmajer commented on src/org/ods/orchestration/usecase/LeVADocumentUseCase.groovy
> +            def docChapterKeys = collectDocChaptersKeys(docChapters)
Same here. `compute`?

2021-05-19 07:02 UTC, clemensutschig commented
@metmajer - we go now the extra route .. more tests, more components, more everything

2021-05-21 06:04 UTC, clemensutschig approved these changes

2021-05-21 06:47 UTC, clemensutschig commented on src/org/ods/orchestration/usecase/LeVADocumentUseCase.groovy
> +    private List<Map> testIssuesTestForTCP(List<Project.JiraDataItem> testIssues) {
`compute` plesase - for consistency ..

2021-05-21 10:29 UTC, merged